# Copyright (C) 2025 Monadfix OÜ
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# See https://doc.traefik.io/traefik

# NOTE: for local traffic we don't care about http/https because we use port :8000 and it's hard or impossible to serve
# both http and https on the same port. So we only serve https.
entryPoints:
  websecure:
    address: ':443'

providers:
  file:
    filename: '/etc/traefik/traefik_dynamic.yaml'
    watch: true

accessLog: {}